version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
        environment:
          NPM_CONFIG_COLOR: false
          NVM_DIR: /home/circleci/.nvm
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - nvm-cache-{{ checksum ".circleci/config.yml" }}
      - run: curl https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
      - save_cache:
          key: nvm-cache-{{ checksum ".circleci/config.yml" }}
          paths:
            - /home/circleci/.nvm
      - run:
          name: npm install && npm test
          command: |
            test_with_version() {
              source "$NVM_DIR/nvm.sh"
              nvm install $1
              nvm exec $1 npm install
              nvm exec $1 npm test
            }
            case $CIRCLE_NODE_INDEX in
              0) test_with_version 6 ;;
              1) test_with_version 8 ;;
              2) test_with_version 10 ;;
              3) npm install && npm test ;;
            esac
